{{-- Modals for selecting investigations --}}
<div
    wire:ignore.self
    class="modal fade"
    id="ai-treatments-modal"
    tabindex="-1"
    aria-labelledby="#ai-treatments-modal"
    aria-hidden="true"
>
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title fw-semibold" style="font-size: 25px" id="#ai-treatments-modal">
                    View AI Treatments
                </h5>

                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>
                    <strong>N/B:</strong>
                    <br />
                    <span class="text-danger">
                        Suggested Treatment for the diagnosis.
                        <br />
                        Please note that these treatments are generated by AI.
                    </span>
                </p>

                <div class="accordion" id="ai_treatmentsAccordion">
                    @forelse ($this->ai_treatments ?? [] as $key => $treatments)
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="heading{{ $key }}">
                                <button
                                    class="accordion-button {{ $key > array_key_first($this->ai_treatments) ? 'collapsed' : '' }}"
                                    type="button"
                                    data-bs-toggle="collapse"
                                    data-bs-target="#collapse{{ $key }}"
                                    aria-expanded="{{ $key === array_key_first($this->ai_treatments) ? 'true' : 'false' }}"
                                    aria-controls="collapse{{ $key }}"
                                >
                                    {{ $key }}
                                </button>
                            </h2>
                            <div
                                id="collapse{{ $key }}"
                                class="accordion-collapse collapse {{ $key === array_key_first($this->ai_treatments) ? 'show' : '' }}"
                                aria-labelledby="heading{{ $key }}"
                                data-bs-parent="#treatmentsAccordion"
                            >
                                <div class="accordion-body">
                                    <strong>Related Treatments:</strong>
                                    <ul>
                                        @foreach ($treatments as $treatment)
                                            <li>{{ $treatment['treatment_name'] }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            </div>
                        </div>
                    @empty
                        <div>No Result Found</div>
                    @endforelse
                </div>
            </div>
        </div>
    </div>
</div>
