INSERT INTO `allergy_reactions` (`id`, `created_at`, `updated_at`, `allergy_reaction`, `status`) VALUES (1, NULL, NULL, 'Anaemia', 'Active');
INSERT INTO `allergy_reactions` (`id`, `created_at`, `updated_at`, `allergy_reaction`, `status`) VALUES (2, NULL, NULL, 'Anaphylaxis', 'Active');
INSERT INTO `allergy_reactions` (`id`, `created_at`, `updated_at`, `allergy_reaction`, `status`) VALUES (3, NULL, NULL, 'Angioedema', 'Active');
INSERT INTO `allergy_reactions` (`id`, `created_at`, `updated_at`, `allergy_reaction`, `status`) VALUES (4, NULL, NULL, 'Arrhythmia', 'Active');
INSERT INTO `allergy_reactions` (`id`, `created_at`, `updated_at`, `allergy_reaction`, `status`) VALUES (5, NULL, NULL, 'Bronchospasm', 'Active');
INSERT INTO `allergy_reactions` (`id`, `created_at`, `updated_at`, `allergy_reaction`, `status`) VALUES (6, NULL, NULL, 'Cough', 'Active');
INSERT INTO `allergy_reactions` (`id`, `created_at`, `updated_at`, `allergy_reaction`, `status`) VALUES (7, NULL, NULL, 'Diarrhea', 'Active');
INSERT INTO `allergy_reactions` (`id`, `created_at`, `updated_at`, `allergy_reaction`, `status`) VALUES (8, NULL, NULL, 'Dystonia', 'Active');
INSERT INTO `allergy_reactions` (`id`, `created_at`, `updated_at`, `allergy_reaction`, `status`) VALUES (9, NULL, NULL, 'Fever', 'Active');
INSERT INTO `allergy_reactions` (`id`, `created_at`, `updated_at`, `allergy_reaction`, `status`) VALUES (10, NULL, NULL, 'Flushing', 'Active');
INSERT INTO `allergy_reactions` (`id`, `created_at`, `updated_at`, `allergy_reaction`, `status`) VALUES (11, NULL, NULL, 'GI upset', 'Active');
INSERT INTO `allergy_reactions` (`id`, `created_at`, `updated_at`, `allergy_reaction`, `status`) VALUES (12, NULL, NULL, 'Headache', 'Active');
INSERT INTO `allergy_reactions` (`id`, `created_at`, `updated_at`, `allergy_reaction`, `status`) VALUES (13, NULL, NULL, 'Hepatotoxicity', 'Active');
INSERT INTO `allergy_reactions` (`id`, `created_at`, `updated_at`, `allergy_reaction`, `status`) VALUES (14, NULL, NULL, 'Hives', 'Active');
INSERT INTO `allergy_reactions` (`id`, `created_at`, `updated_at`, `allergy_reaction`, `status`) VALUES (15, NULL, NULL, 'Hypertension', 'Active');
INSERT INTO `allergy_reactions` (`id`, `created_at`, `updated_at`, `allergy_reaction`, `status`) VALUES (16, NULL, NULL, 'Itching', 'Active');
INSERT INTO `allergy_reactions` (`id`, `created_at`, `updated_at`, `allergy_reaction`, `status`) VALUES (17, NULL, NULL, 'Mental status change', 'Active');
INSERT INTO `allergy_reactions` (`id`, `created_at`, `updated_at`, `allergy_reaction`, `status`) VALUES (18, NULL, NULL, 'Musculoskeletal pain', 'Active');
INSERT INTO `allergy_reactions` (`id`, `created_at`, `updated_at`, `allergy_reaction`, `status`) VALUES (19, NULL, NULL, 'Myalgia', 'Active');
INSERT INTO `allergy_reactions` (`id`, `created_at`, `updated_at`, `allergy_reaction`, `status`) VALUES (20, NULL, NULL, 'Vomiting', 'Active');
INSERT INTO `allergy_reactions` (`id`, `created_at`, `updated_at`, `allergy_reaction`, `status`) VALUES (21, NULL, NULL, 'face swells', 'Active');
INSERT INTO `allergy_reactions` (`id`, `created_at`, `updated_at`, `allergy_reaction`, `status`) VALUES (22, NULL, NULL, 'ERYTHEMA MULTIFORME', 'Active');
