INSERT INTO `allergies` (`id`, `created_at`, `updated_at`, `group_name`, `allergy_name`, `status`) VALUES (1, NULL, NULL, 'Drug', 'ACE inhibitors', 'Active');
INSERT INTO `allergies` (`id`, `created_at`, `updated_at`, `group_name`, `allergy_name`, `status`) VALUES (2, NULL, NULL, 'Drug', 'Aspirin', 'Active');
INSERT INTO `allergies` (`id`, `created_at`, `updated_at`, `group_name`, `allergy_name`, `status`) VALUES (3, NULL, NULL, 'Drug', 'Codeine', 'Active');
INSERT INTO `allergies` (`id`, `created_at`, `updated_at`, `group_name`, `allergy_name`, `status`) VALUES (4, NULL, NULL, 'Drug', 'Cephalosporins', 'Active');
INSERT INTO `allergies` (`id`, `created_at`, `updated_at`, `group_name`, `allergy_name`, `status`) VALUES (5, NULL, NULL, 'Drug', 'Erythromycins', 'Active');
INSERT INTO `allergies` (`id`, `created_at`, `updated_at`, `group_name`, `allergy_name`, `status`) VALUES (6, NULL, NULL, 'Drug', 'Heparins', 'Active');
INSERT INTO `allergies` (`id`, `created_at`, `updated_at`, `group_name`, `allergy_name`, `status`) VALUES (7, NULL, NULL, 'Drug', 'NSAIDs', 'Active');
INSERT INTO `allergies` (`id`, `created_at`, `updated_at`, `group_name`, `allergy_name`, `status`) VALUES (8, NULL, NULL, 'Drug', 'Penicillins', 'Active');
INSERT INTO `allergies` (`id`, `created_at`, `updated_at`, `group_name`, `allergy_name`, `status`) VALUES (9, NULL, NULL, 'Drug', 'Statins', 'Active');
INSERT INTO `allergies` (`id`, `created_at`, `updated_at`, `group_name`, `allergy_name`, `status`) VALUES (10, NULL, NULL, 'Drug', 'Sulfonamides', 'Active');
INSERT INTO `allergies` (`id`, `created_at`, `updated_at`, `group_name`, `allergy_name`, `status`) VALUES (11, NULL, NULL, 'Environment', 'Adhesive tape', 'Active');
INSERT INTO `allergies` (`id`, `created_at`, `updated_at`, `group_name`, `allergy_name`, `status`) VALUES (12, NULL, NULL, 'Environment', 'Bee stings', 'Active');
INSERT INTO `allergies` (`id`, `created_at`, `updated_at`, `group_name`, `allergy_name`, `status`) VALUES (13, NULL, NULL, 'Environment', 'Dust', 'Active');
INSERT INTO `allergies` (`id`, `created_at`, `updated_at`, `group_name`, `allergy_name`, `status`) VALUES (14, NULL, NULL, 'Environment', 'Latex', 'Active');
INSERT INTO `allergies` (`id`, `created_at`, `updated_at`, `group_name`, `allergy_name`, `status`) VALUES (15, NULL, NULL, 'Environment', 'Mold', 'Active');
INSERT INTO `allergies` (`id`, `created_at`, `updated_at`, `group_name`, `allergy_name`, `status`) VALUES (16, NULL, NULL, 'Environment', 'Pollen', 'Active');
INSERT INTO `allergies` (`id`, `created_at`, `updated_at`, `group_name`, `allergy_name`, `status`) VALUES (17, NULL, NULL, 'Environment', 'Ragweed', 'Active');
INSERT INTO `allergies` (`id`, `created_at`, `updated_at`, `group_name`, `allergy_name`, `status`) VALUES (18, NULL, NULL, 'Environment', 'Smoky Environment', 'Active');
INSERT INTO `allergies` (`id`, `created_at`, `updated_at`, `group_name`, `allergy_name`, `status`) VALUES (19, NULL, NULL, 'Food', 'Beef', 'Active');
INSERT INTO `allergies` (`id`, `created_at`, `updated_at`, `group_name`, `allergy_name`, `status`) VALUES (20, NULL, NULL, 'Food', 'Caffeine', 'Active');
INSERT INTO `allergies` (`id`, `created_at`, `updated_at`, `group_name`, `allergy_name`, `status`) VALUES (21, NULL, NULL, 'Food', 'Chocolate', 'Active');
INSERT INTO `allergies` (`id`, `created_at`, `updated_at`, `group_name`, `allergy_name`, `status`) VALUES (22, NULL, NULL, 'Food', 'products', 'Active');
INSERT INTO `allergies` (`id`, `created_at`, `updated_at`, `group_name`, `allergy_name`, `status`) VALUES (23, NULL, NULL, 'Food', 'Eggs', 'Active');
INSERT INTO `allergies` (`id`, `created_at`, `updated_at`, `group_name`, `allergy_name`, `status`) VALUES (24, NULL, NULL, 'Food', 'Fish', 'Active');
INSERT INTO `allergies` (`id`, `created_at`, `updated_at`, `group_name`, `allergy_name`, `status`) VALUES (25, NULL, NULL, 'Food', 'Milk protein', 'Active');
INSERT INTO `allergies` (`id`, `created_at`, `updated_at`, `group_name`, `allergy_name`, `status`) VALUES (26, NULL, NULL, 'Food', 'Peanuts', 'Active');
INSERT INTO `allergies` (`id`, `created_at`, `updated_at`, `group_name`, `allergy_name`, `status`) VALUES (27, NULL, NULL, 'Food', 'Shellfish', 'Active');
INSERT INTO `allergies` (`id`, `created_at`, `updated_at`, `group_name`, `allergy_name`, `status`) VALUES (28, NULL, NULL, 'Food', 'Soy', 'Active');
INSERT INTO `allergies` (`id`, `created_at`, `updated_at`, `group_name`, `allergy_name`, `status`) VALUES (29, NULL, NULL, 'Food', 'Strawberries', 'Active');
INSERT INTO `allergies` (`id`, `created_at`, `updated_at`, `group_name`, `allergy_name`, `status`) VALUES (30, NULL, NULL, 'Food', 'Wheat', 'Active');
INSERT INTO `allergies` (`id`, `created_at`, `updated_at`, `group_name`, `allergy_name`, `status`) VALUES (31, NULL, NULL, 'Other', 'hayfever', 'Active');
INSERT INTO `allergies` (`id`, `created_at`, `updated_at`, `group_name`, `allergy_name`, `status`) VALUES (32, NULL, NULL, 'Other', 'PAPER', 'Active');
INSERT INTO `allergies` (`id`, `created_at`, `updated_at`, `group_name`, `allergy_name`, `status`) VALUES (33, NULL, NULL, 'Other', 'No known allergies', 'Active');
INSERT INTO `allergies` (`id`, `created_at`, `updated_at`, `group_name`, `allergy_name`, `status`) VALUES (34, NULL, NULL, 'Other', 'No known allergy', 'Active');
INSERT INTO `allergies` (`id`, `created_at`, `updated_at`, `group_name`, `allergy_name`, `status`) VALUES (35, NULL, NULL, 'Other', 'dust', 'Active');
INSERT INTO `allergies` (`id`, `created_at`, `updated_at`, `group_name`, `allergy_name`, `status`) VALUES (36, NULL, NULL, 'Other', 'Vomiting', 'Active');
